// <auto-generated />
namespace BIMSWebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AddedResident : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedResident));
        
        string IMigrationMetadata.Id
        {
            get { return "201901231443405_AddedResident"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
